### ISSUE TITLE
Leaflet CoordinatedImagePreview plugin is not updating images when zooming / moving a map

### ISSUE THREAD

**Issue by mngorny** [utahemre/Leaflet.CoordinatedImagePreview#1]
Hi Everybody

Could you please check if there is a bug in this plugin (Leaflet.CoordinatedImagePreview)?

It's showing the coordinated images from geojson properly but when moving or zooming a map the list of images is not updating. It looks like it is showing all the images from geojson, not only these which are in current map bounds

I have this problem in my project but appearently the same problem is in the demo: 
https://utahemre.github.io/coordinatedimagepreviewdemo.html

So I guess there is a problem in the code??

Thanks in advance!

**Comment by utahemre** [comment]
Hi,

This is not a bug. In demo project there is no restful service. There is a static json file so the results are always same. In every zooming and panning plugin sends new request. You have to manage the results in your restful service. Plugin not control the results in active bounds or not. But this feature could be added.

**Comment by mngorny** [comment]
Hi 

Thanks for quick reply
Could you please add this feature to the plugin? It would be a great advantage.

**Comment by utahemre** [comment]
This feature has been added.
